---
version: 2
executorType: docker
containerInfo:
  - image: dickeyxxx/cli-engine-docker:v1.2.3
stages:
  build:
    workDir: ~/cli
    steps:
      - type: checkout
      - type: cache-restore
        key: cli
      - type: shell
        command: |
          set -exu
          yarn config set registry https://cli-npm.heroku.com
          yarn
          ./bin/run version
          ./bin/run help
      - type: cache-save
        key: cli
        paths:
          - /usr/local/share/.cache/yarn
      - type: deploy
        shell: /bin/bash
        command: |
          set -e
          echo $HEROKU_DEB_KEY | base64 -d | gpg --import
          echo "machine api.heroku.com" >> ~/.netrc
          echo "    password $HEROKU_API_KEY" >> ~/.netrc
          echo "    jeff+devcenter@heroku.com" >> ~/.netrc
          set -ex
          TAG=`git describe --exact-match HEAD || echo NOTAG`
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            yarn run release beta
            ./scripts/release-deb beta
          fi
          if [ "${TAG}" != "NOTAG" ]; then
            yarn run release stable
            ./scripts/release-deb stable
            ./scripts/generate_docs.sh > /tmp/cli_documentation.md
          fi
          if [ "${CIRCLE_BRANCH}" == "auto-doc" ]; then
            ./scripts/generate_docs.sh > /tmp/cli_documentation.md
            declare -x LANG="en_US.UTF-8"
            devcenter push /tmp/heroku-cli-commands.md --trace
          fi
          if [ "${CIRCLE_BRANCH}" == "dev" ]; then
            yarn run release dev
            ./scripts/release-deb dev
          fi
